name: Enhancement Request
description: Describe a new enhancement
title: "Enhancement: "
labels: ["enhancement", "needs triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a enhancement in the project. Please fill out the information below to the best of your ability. If you have a possible solution or workaround, please describe it.
  - type: textarea
    id: enhancement-description
    attributes:
      label: Enhancement Description
      description: A clear and concise description of what the enhancement is.
      placeholder: Describe the enhancement
    validations:
      required: true
  - type: textarea
    id: enhancement-usecase
    attributes:
      label: Use Case
      description: Why do you need this enhancement?
      placeholder: Describe the use case for this enhancement
    validations:
      required: true
  - type: textarea
    id: enhancement-solution
    attributes:
      label: Possible Solution
      description: If you have a possible solution or workaround, please describe it.
      placeholder: If you have any ideas or suggestions on how this enhancement could be implemented, please share them here.
    validations:
      required: false
  - type: textarea
    id: enhancement-related
    attributes:
      label: Related Issues
      description: List any related issues here.
      placeholder: Are there any related issues?
    validations:
      required: false
