name: Feature Request
description: Describe a new feature
title: "Feature: "
labels: ["feature", "needs triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature in the project. Please fill out the information below to the best of your ability. If you have a possible solution or workaround, please describe it.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of what the feature is.
      placeholder: Describe the feature
    validations:
      required: true
  - type: textarea
    id: feature-usecase
    attributes:
      label: Use Case
      description: Why do you need this feature?
      placeholder: Describe the use case for this feature
    validations:
      required: true
  - type: textarea
    id: feature-solution
    attributes:
      label: Possible Solution
      description: If you have a possible solution or workaround, please describe it.
      placeholder: If you have any ideas or suggestions on how this feature could be implemented, please share them here.
    validations:
      required: false
  - type: textarea
    id: feature-related
    attributes:
      label: Related Issues
      description: List any related issues here.
      placeholder: Are there any related issues?
    validations:
      required: false
