name: Release Helm Charts

on:
  push:
    branches:
      - master

jobs:
  cern-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Run deploy script
        run: ./.github/scripts/deploy.sh
        shell: bash
        env:
          HARBOR_USERNAME: "${{ secrets.HARBOR_USERNAME }}"
          HARBOR_TOKEN: "${{ secrets.HARBOR_TOKEN }}"
          
  oci-rucio-consistency:
    runs-on: ubuntu-latest
    steps:
    - name: Push Helm chart to OCI compatible registry (Github)
      uses: bsord/helm-push@v4.1.0
      with:
        useOCIRegistry: true
        registry-url:  oci://registry.cern.ch/${{ secrets.HARBOR_USERNAME }}/helm-rucio-consistency
        username: ${{ secrets.HARBOR_USERNAME }}
        access-token: ${{ secrets.HARBOR_TOKEN }}
        force: true
        chart-folder: CMSRucio/helm/rucio-consistency

  
