name: Release Helm Charts

on:
  push:
    branches:
      - master

jobs:
  cern-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Run deploy script
        run: ./.github/scripts/deploy.sh
        shell: bash
        env:
          HARBOR_USERNAME: "${{ secrets.HARBOR_USERNAME }}"
          HARBOR_TOKEN: "${{ secrets.HARBOR_TOKEN }}"
